### ISSUE TITLE
How did you got an Intern @TwitterOSS?

### ISSUE THREAD

**Issue by ParthS007** [OrkoHunter/ama#2]
#### I want to ask about the above question.
- How did you prepare for it?
- What are the requirements/eligibility criterion?

#### Introduction
- I am GSoC Intern 2018.
- I am a Pre-Final Engineering Student.

_PS: I searched but didn't get a perfect answer to these question_ :worried:

**Comment by OrkoHunter** [comment]
Hi Parth!

Twitter has a bit different interview procedure than its competitors. The Open Source team here saw my application for an internship. They set me up for a couple of interviews. The interviews were not about hardcore competitive coding, but rather a discussion on the projects I have worked on.
I think you can find the criterion over [here](https://careers.twitter.com/en/university.html). Watch this page and apply early (valid for all the companies).

**Comment by ParthS007** [comment]
Thanks for the answer. :smiley: 

Is this different than an SDE Intern or both are same?

**Comment by OrkoHunter** [comment]
Same. :)

**Comment by ParthS007** [comment]
Thanks for answering my queries.
You can close this Issue.

PS: What are the other ways to contact you?

**Comment by OrkoHunter** [comment]
I love emails! :D himanshu.mishra.kgp@gmail.com
